class Autogenerated {
  List<HotSales>? homeStore;
  List<BestSeller>? bestSeller;

  Autogenerated({this.homeStore, this.bestSeller});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['home_store'] != null) {
      homeStore = <HotSales>[];
      json['home_store'].forEach((v) {
        homeStore!.add(new HotSales.fromJson(v));
      });
    }
    if (json['best_seller'] != null) {
      bestSeller = <BestSeller>[];
      json['best_seller'].forEach((v) {
        bestSeller!.add(new BestSeller.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.homeStore != null) {
      data['home_store'] = this.homeStore!.map((v) => v.toJson()).toList();
    }
    if (this.bestSeller != null) {
      data['best_seller'] = this.bestSeller!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class HotSales {
  int? id;
  bool? isNew;
  String? title;
  String? subtitle;
  String? picture;
  bool? isBuy;

  HotSales(
      {this.id,
        this.isNew,
        this.title,
        this.subtitle,
        this.picture,
        this.isBuy});

  HotSales.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    isNew = json['is_new'];
    title = json['title'];
    subtitle = json['subtitle'];
    picture = json['picture'];
    isBuy = json['is_buy'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['is_new'] = this.isNew;
    data['title'] = this.title;
    data['subtitle'] = this.subtitle;
    data['picture'] = this.picture;
    data['is_buy'] = this.isBuy;
    return data;
  }
}

class BestSeller {
  int? id;
  bool? isFavorites;
  String? title;
  int? priceWithoutDiscount;
  int? discountPrice;
  String? picture;

  BestSeller(
      {this.id,
        this.isFavorites,
        this.title,
        this.priceWithoutDiscount,
        this.discountPrice,
        this.picture});

  BestSeller.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    isFavorites = json['is_favorites'];
    title = json['title'];
    priceWithoutDiscount = json['price_without_discount'];
    discountPrice = json['discount_price'];
    picture = json['picture'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['is_favorites'] = this.isFavorites;
    data['title'] = this.title;
    data['price_without_discount'] = this.priceWithoutDiscount;
    data['discount_price'] = this.discountPrice;
    data['picture'] = this.picture;
    return data;
  }
}